name = "food"
compatibility_date = "2026-04-10"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[[d1_databases]]
binding = "recipes_db"
database_name = "recipes-db"
database_id = "a3fb34ca-59ac-4f2e-bdfc-a983e289da0d"
